export default [
    {
        name: 'Variable',
        fields: [
            {name: 'name', hideFor: 'FormImage'},
            'fieldValue',
            'label',
            'dataFormat',
            'dataMask',
            'validation',
            'readonly',
            'disabled',
            'initiallyChecked',
            'screen',
            'multipleUpload',
        ],
        open: true,
    },
    {
        name: 'Configuration',
        fields: [
            {name: 'name', showFor: 'FormImage'},
            'image',
            'eventData',
            'tooltip',
            'type',
            'placeholder',
            'content',
            'helper',
            'Multiselect checkbox (doesn’t exist)',
            'richtext',
            'rows',
            {name: 'options', showFor: 'FormMultiColumn'},
            'form',
            'editable',
            'height_ag_grid',
            'help_editor',
            'orientation',
        ],
        open: false,
    },
    {
        name: (control) => control.component === 'FormRecordList' ? 'Columns' : 'Data Source',
        fields: [
            'fields',
            {name: 'options', hideFor: 'FormMultiColumn'},
            'steps',
        ],
        open: false,
    },
    {
        name: 'Design',
        fields: ['color', 'bgcolor', 'variant', 'toggle', 'height', 'width', 'thcolor'],
        open: false,
    },
    {
        name: 'Advanced',
        fields: ['conditionalHide', 'customCssSelector', 'defaultValue',
            {name: 'customFormatter', showFor: 'FormInput'},
            {name: 'ariaLabel', showFor: 'FormInput'},
            {name: 'ariaLabel', showFor: 'FormSelectList'},
            {name: 'ariaLabel', showFor: 'FormDatePicker'},
            {name: 'ariaLabel', showFor: 'FormCheckbox'},
            {name: 'ariaLabel', showFor: 'FormDatePicker'},
            {name: 'ariaLabel', showFor: 'FileUpload'},
            {name: 'ariaLabel', showFor: 'FileDownload'},
            {name: 'ariaLabel', showFor: 'FormSelectList'},
            {name: 'ariaLabel', showFor: 'FormButton'},
            {name: 'ariaLabel', showFor: 'FormTextArea'},
            {name: 'tabindex', showFor: 'FormInput'},
            {name: 'tabindex', showFor: 'FormSelectList'},
            {name: 'tabindex', showFor: 'FormDatePicker'},
            {name: 'tabindex', showFor: 'FormCheckbox'},
            {name: 'tabindex', showFor: 'FormDatePicker'},
            {name: 'tabindex', showFor: 'FileUpload'},
            {name: 'tabindex', showFor: 'FileDownload'},
            {name: 'tabindex', showFor: 'FormSelectList'},
            {name: 'tabindex', showFor: 'FormButton'},
            {name: 'tabindex', showFor: 'FormTextArea'},
            {name: 'tabindex', showFor: 'FormTimeline'},
        ],
        open: false,
    },
];
